### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by barkls** [phys201/bayboone#21]
An io test is failing to read in the test data file. My guess is that the hard-coded filepath isn't being found when tests are run from different locations. You should use a relative filepath to locate the data file relative to the test location.
```
Traceback (most recent call last):
  File "C:\Users\Solomon\bayboone\bayboone\tests\test_io.py", line 29, in test_write_read
    data = Data.load('testing.csv')
  File "C:\Users\Solomon\bayboone\bayboone\data_io.py", line 39, in load
    N_numu = int(row[0])
IndexError: list index out of range
```

**Comment by tcontrer** [comment]
Added get_data_file_path to search for the file path on any computer. commit #37
