### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by jennmcguire** [phys201/bayboone#38]
```
.....E.....
======================================================================
ERROR: Tests the that write_data and load funcion correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jenna\Documents\GitHub\bayboone\bayboone\tests\test_io.py", line 29, in test_write_read
    data = Data.load('testing.csv')
  File "C:\Users\jenna\Documents\GitHub\bayboone\bayboone\data_io.py", line 37, in load
    with open(filepath, mode='r') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jenna\\Documents\\GitHub\\bayboone\\bayboone\\data\\testing.csv'

----------- coverage: platform win32, python 3.9.4-final-0 -----------
Name                             Stmts   Miss  Cover
----------------------------------------------------
bayboone\__init__.py                 3      2    33%
bayboone\data_io.py                 52      7    87%
bayboone\inference\__init__.py       0      0   100%
bayboone\inference\module.py        56     20    64%
bayboone\tests\__init__.py           0      0   100%
bayboone\tests\test_io.py           30      2    93%
bayboone\tests\test_module.py       31      0   100%
setup.py                             2      2     0%
----------------------------------------------------
TOTAL                              174     33    81%
----------------------------------------------------------------------
Ran 11 tests in 139.050s

FAILED (errors=1)
```

**Comment by jennmcguire** [comment]
This error seems to stem from testing.csv being in a different location in your package than the path specified in your test function

**Comment by tcontrer** [comment]
Fixed loading and writing functions to work anywhere! #43
